version: '3.8'
services:
  IPL-app:
    build: .
    image: ipl-app:v1.0.0
    container_name: IPL-app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ipl
    # If you need to mount code for live changes
    # volumes:
    #   - .:/usr/src/app
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
